### ISSUE TITLE
Problème pour enregistrer la map

### ISSUE THREAD

**Issue by Lindoryel** [Lindoryel/javascript_game#10]
On n'arrive pas à trouver comment enregistrer une map dessinée, puis ensuite en cliquant sur un bouton la redessiner entièrement... Utiliser JSON ? Du PHP pour écrire des fichiers ?

**Comment by Lindoryel** [comment]
Sachant que l'on veut garder la map sous forme d'un tableau d'objets, on ne veut pas appliquer une image au canvas

**Comment by micbuffa** [comment]
Il existe plusieurs systèmes de persistence :

   - Avec un serveur (mais je conseille pas dans ce cours) et des avec des
   WebServices (au programme en M1), que ce soit en Java, PHP, NodeJS, Python
   etc.
   - Avec des services du cloud (programme de M2)
   - Mais je vous conseille d'utiliser un système de persistence simple :
   avec un console.log(JSON.stringify(votre_map_objet_ou_tableau_JS) vous
   ecrivez l'objet dans la console de debug, et vous copiez collez ceci dans
   un bout de votre code, par exemple dans le fichier maps.js qui contient un
   tableau de maps:
   - let maps = [];

Vous ajoutez une ligne :
maps.push( et ici vous collez ce que vous aviez généré dans la console).

En gros, vous codez en dur les maps générées. Et le fichier maps.js est
bien sur chargé par votre programme, dans le index.html avec un script src,
ou avec un import....

Il existe aussi des mécanismes de persistence dans le browser, mais ce
n'est pas adapté à ce que vous voulez faire.

Exemple de ce que je viens d'expliquer : regardez cette webapp :
https://mainline.i3s.unice.fr/AmpSim4/
Si vous changez les boutons de place, les sliders etc, vous pouvez sauver
la config en cliquant le bouton au centre "show current settings in
console" :
[image: image.png]
ouvrez la console, vous verrez un truc comme :

[image: image.png]

et bien, quand je fais un preset pour cet ampli, que je veux le proposer en
standard dans le menu des presets (sous le bouton "show current
config..."), je copie/colle cet objet dans le code de
ressources/presets.js  (faites click droit / view source) :
https://mainline.i3s.unice.fr/AmpSim4/ressources/presets.js

On voit :

var preset1 = {
  name: "Hard Rock classic 1",
  boost: false,
  LS1Freq: 720,
  LS1Gain: -6,
  LS2Freq: 320,
  LS2Gain: -5,
  gain1: 1,
  distoName1: "asymetric",
  K1: "7.8",
  HP1Freq: 6,
  HP1Q: 0.707099974155426,
  LS3Freq: 720,
  LS3Gain: -6,
  gain2: 1,
  distoName2: "notSoDistorded",
  K2: "7.8",
  OG: "7.0",
  BF: "8.2",
  MF: "8.2",
  TF: "3.8",
  PF: "6.9",
  EQ: [5, 11, -6, -10, 7, 2],
  MV: "7.2",
  RN: "Fender Hot Rod",
  RG: "2.0",
  CN: "Marshall 1960, axis",
  CG: "9.4"
};

var preset2 = {
  name: "Clean and Warm",
  boost: false,
  LS1Freq: 720,
  LS1Gain: -6,
  LS2Freq: 320,
  LS2Gain: 1.600000023841858,
  gain1: 1,
  distoName1: "asymetric",
  K1: "7.8",
  HP1Freq: 6,
  HP1Q: 0.707099974155426,
  LS3Freq: 720,
  LS3Gain: -6,
  gain2: 1,
  distoName2: "standard",
  K2: "0.9",
  OG: "7.0",
  BF: "6.7",
  MF: "7.1",
  TF: "3.2",
  PF: "6.9",
  EQ: [10, 5, -7, -7, 12, 0],
  MV: "7.2",
  RN: "Fender Hot Rod",
  RG: "1.4",
  CN: "Marshall 1960, axis",
  CG: "8.8"
};

et dans le fichier amp.js on a :


function initPresets() {
    // presets are added from the preset repertory
    // here presets are js variables
    presets.push(preset1);
    presets.push(preset2);
    presets.push(preset3);
    presets.push(preset4);
    presets.push(preset5);
    presets.push(preset6);
    presets.push(preset7);
    presets.push(preset8);
    presets.push(preset9);
    presets.push(preset10);
    presets.push(preset11);
    presets.push(preset12);
    presets.push(preset13);
    presets.push(preset14);
    presets.push(preset15);
    presets.push(preset16);
    presets.push(preset17);
    presets.push(preset18);
    presets.push(preset19);
    presets.push(preset20);
    presets.push(preset21);
  }

**Comment by Lindoryel** [comment]
Merci pour votre réponse si rapide ! J'ai tâché de suivre vos conseils mais j'ai un problème toujours, notre map est un tableau composé d'objets (sol arbres eau herbe...) qui ont des caractéristiques (taille, couleur) mais aussi des collisions etc. Lorsque je récupère le code de la console avec un JSON.stringify, cela récupère les caractéristiques de mes objets, mais le fait que ce sont des objets passe à la trappe : cela donne que la map ne se dessine pas (lorsque je fais map = sauvegarde, cela donne un fond uniforme gris, mais dans la console map prend bien les valeurs de sauvegarde), et si elle se dessinait en l'état ce qui est dedans ne serait pas reconnu comme les objets, et du coup je ne pense pas que les collisions fonctionneraient... pour l'instant on ne fait qu'une map, je vous montre le code (j'ai bien lié avec un script dans le html, et la map se charge lorsque je clique sur un îcone qui appelle la fonction loadMap)
[maps.zip](https://github.com/Lindoryel/javascript_game/files/3883213/maps.zip)


![variableSauvegarde](https://user-images.githubusercontent.com/28755781/69489764-f7d73b00-0e7d-11ea-9626-88bfe0a89599.png)
![variableMap](https://user-images.githubusercontent.com/28755781/69489773-09204780-0e7e-11ea-8b3b-25a3b7bb97c7.png)

**Comment by Lindoryel** [comment]
Pour les images, la première c'est ce que j'ai dans sauvegarde comme type de données, et sur la deuxième image c'est comment est composée map initialement (on voit que dans sauvegarde on ne fait jamais référence à sol arbres ou autre, alors que c'est le cas dans map)

**Comment by micbuffa** [comment]
Oui, quand on sérialise on ne sérialise pas le code, mais les données (les
propriétés). Il te faut ensuite coller les données affichées par
JSON.stringify dans un fichiers maps_precalculées.js et creer une fonction
setCurrentMap(map) dans ta classe Map pour charger.

**Comment by Lindoryel** [comment]
Je n'avais pas vu votre réponse, désolée pour le retard...au final j'ai trouvé la réponse en testant et en réfléchissant, j'arrive à charger la map enregistrée ! Et les collisions fonctionnent, donc on va pouvoir continuer ! Merci encore pour votre aide !
